name: CI - Build and Push Docker Images

on:
    workflow_run:
        workflows: ['CI - Laravel Tests']
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: read
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image (app)
              id: build_app
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/task-app-ci-cd-demo:latest
                      ${{ secrets.DOCKER_USERNAME }}/task-app-ci-cd-demo:${{ github.sha }}
                  cache-from: type=gha,scope=app
                  cache-to: type=gha,mode=max,scope=app

            - name: Build and push Nginx image
              id: build_nginx
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.nginx
                  push: true
                  build-args: |
                      APP_IMAGE=${{ secrets.DOCKER_USERNAME }}/task-app-ci-cd-demo:${{ github.sha }}
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/task-app-nginx:latest
                      ${{ secrets.DOCKER_USERNAME }}/task-app-nginx:${{ github.sha }}
                  cache-from: type=gha,scope=nginx
                  cache-to: type=gha,mode=max,scope=nginx

            - name: Scan app image with Trivy
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: ${{ secrets.DOCKER_USERNAME }}/task-app-ci-cd-demo:${{ github.sha }}
                  format: 'table'
                  ignore-unfixed: true
                  vuln-type: 'os,library'
                  severity: 'CRITICAL,HIGH'
                  exit-code: '1'

            - name: Scan nginx image with Trivy
              uses: aquasecurity/trivy-action@0.20.0
              with:
                  image-ref: ${{ secrets.DOCKER_USERNAME }}/task-app-nginx:${{ github.sha }}
                  format: 'table'
                  ignore-unfixed: true
                  vuln-type: 'os,library'
                  severity: 'CRITICAL,HIGH'
                  exit-code: '1'
